### PR TITLE
Add VRS logo to header

### LINKED ISSUE #21: Add VRS Logo to header bar
Have VRS logo next to title in header bar.

### PR DESCRIPTION
**Pull request by halyngoc**
Resolves #21.

Added a new [VRS logo png](https://github.com/halyngoc/pdx-robotics.github.io/blob/aa985b26aa8b24255877bb39608743a894bd3ce5/images/vrs_logo_white_transparentbg.png) because the current one's background color doesn't match with the header.

I set the logo height to the full height of header just cause it sounds cool. A quick fix if it ends up looking bad.

### CODE REVIEW

**Comment by halyngoc** [comment]
It's still there if I did it right.

**Comment by Chana030102** [comment]
Tested the changes. The logo probably needs to be smaller so that we get more border around it. Otherwise, that looks like a good spot in the corner with the text next to it.

Look at the image attached here:
logoinheadertest

**Comment by halyngoc** [comment]
Ah, it does look bad after all. Well I can't see the header so @Chana030102 can you fix the height in [this line](https://github.com/pdx-robotics/pdx-robotics.github.io/blob/6a9217be596bf7c21a3bb5b7fd00e1b0e17abed3/parts/header.html#L8)?

**Comment by Chana030102** [comment]
Changing it to about 50% or 60% looks pretty nice.

50%
logo50

60%
logo60

70%
logo70

**Comment by halyngoc** [comment]
I'd say 50%.

**Pull request merged**
